### PR TITLE
Fixed?

### PR DESCRIPTION
**Pull request by lavender-sys**

### CODE REVIEW

**Comment by lavender-sys** [comment]
You commented so fast. Right after I made the pr it showed it.

**Comment by AvgZing** [comment]
Lol I AWESOME!

**Comment by AvgZing** [comment]
Fix conflicts

**Comment by lavender-sys** [comment]
Can you help me? The conflict editor isn't very helpful.

**Comment by AvgZing** [comment]
Soon, gimme 20-30 mins, got a project to finish

**Comment by lavender-sys** [comment]
K. I've tried looking at the conflict editor and tried adding another </div> somewhere, but that didnt work.

**Comment by dragonwocky** [comment]
I'll see if I can fix it.

**Comment by dragonwocky** [comment]
Actually, is it worth the trouble? It looks like we would have to do a full jekyll install with all files here anyway - and it's only 9 lines duplicated and edited for each post anyway....

**Comment by AvgZing** [comment]
No it's not worth it. Especially because the posts wouldn't be on the home page anymore

**Comment by Vaults1** [comment]
It is worth it because it will be easier to do the posts.

**Comment by Vaults1** [comment]
Nope, doesn't work @Dog2puppy .

**Comment by dragonwocky** [comment]
No it isn't worth it @Ultie0. All it takes is copying + pasting + editing 9 lines for a new post atm. If we do this we would be creating whole new files - and all the posts would be on different pages.

**Pull request closed without merging**
