### PR TITLE
Add a list of repos powered by HimbeerCloud™...

### PR DESCRIPTION
**Pull request by HimbeersaftLP**
...and move the News header down

### CODE REVIEW

**Review by AvgZing — CHANGES_REQUESTED** [review]
This is good, other than...
1. We already have a projects page
2. The blocks are horizontal, not responsive to the page

**Review by dragonwocky — CHANGES_REQUESTED** [review]
Nice work, but sorry no. Like @TheRoyalBlock said: we already have a projects page.

**Comment by Vaults1** [comment]
I fell off my chair when I read HimbeerCloud. 😛

**Review by Vaults1 — APPROVED** [review]
# HimbeerCloud!

**Comment by dragonwocky** [comment]
@Ultie0 same xD

**Comment by HimbeersaftLP** [comment]
@TheRoyalBlock The blocks are supposed to be horizontaly scrolling, also, this is not a replacement for the projects page, it's just a quick overview of all our repos

**Comment by lavender-sys** [comment]
I approve because of HimbeerCloud!

**Comment by Dog2puppy** [comment]
Umm.. I cant find the right button.

**Review by lavender-sys — APPROVED** [review]

**Comment by AvgZing** [comment]
even though it's just an overview, so is the projects page. Seriously, there's no need.

**Comment by lavender-sys** [comment]
@TheRoyalBlock I really like it. Mostly because of HimbeerCloud. (Grape juice cloud)

**Review by dragonwocky — APPROVED** [review]

**Comment by dragonwocky** [comment]
I don't really mind, just don't see the need..... HimbeerCloud is pretty funny though xD

**Review by Erkam246 — APPROVED** [review]

**Comment by Vaults1** [comment]
I really want to merge this lol

Also,  how did you get the github stats?

**Comment by HimbeersaftLP** [comment]
Using the [GitHub API](https://api.github.com/orgs/BoxOfDevs/repos)

**Comment by lavender-sys** [comment]
Grape juice cloud! 🍇 🍇 🍇

**Comment by AvgZing** [comment]
There is no need. It's redundant. This is like adding a plugin to a server that adds the /op command, even though it's already in PM.

**Comment by HimbeersaftLP** [comment]
> Grape juice cloud! 🍇 🍇 🍇

*Raspberry juice :P

> There is no need. It's redundant. This is like adding a plugin to a server that adds the /op command, even though it's already in PM.

No, this would be like adding a plugin that adds /thim which tells me a message, even tough /tell HimbeersaftLP is already in PM.

It's just a short overview

**Comment by Ultie0** [comment]
7h12 n33d2 70 83 m3r93D!

**Comment by TheRoyalBlock** [comment]
@ultie0 why are you doing this us? Type normal please

**Comment by Vaults1** [comment]
@TheRoyalBlock This needs to be merged!

**Comment by AvgZing** [comment]
No it doesnt! It is completely irrevalent! If they wanted an overview of the repositories, they would visit our github page. Not that.

**Comment by HimbeersaftLP** [comment]
Know what's irrelevant too? You, deleting and editing the issues on projects you don't even have to do with....

**Comment by AvgZing** [comment]
@HimbeersaftLP I do not know what you are talking about. I am confused.

**Comment by HimbeersaftLP** [comment]
*cough* CommandShop *cough*

**Comment by Vaults1** [comment]
@HimbeersaftLP would you like a cough drop? 😛

**Comment by HimbeersaftLP** [comment]
XD

**Comment by lavender-sys** [comment]
It's 3 agianst 1 @TheRoyalBlock. The majority rules.

**Comment by Vaults1** [comment]
Our main man @Ad5001 needs to respond

**Comment by Ad5001** [comment]
I have no opinion on this.

**Comment by lavender-sys** [comment]
@Ad5001 Please be on our side and approve it!

**Comment by AvgZing** [comment]
Why merge? It adds another page, it makes a list of stuff which can easily be viewed on github anyways!

**Comment by HimbeersaftLP** [comment]
@TheRoyalBlock Aaand what's the projects page for then?

**Comment by Vaults1** [comment]
Shall we do a vote?

**Comment by AvgZing** [comment]
The projects page is for downloading the plugin and viewing the wiki. We will sooon implement a downloads counter onto the projects page. That way they don't need to visit github to download the plugin and view the readme.

**Review by Ad5001 — COMMENTED** [review]
I hvae no opinion on this.

**Comment by Taki21** [comment]
bonjour all but may i ask, how do u approve or dissaprove?

**Comment by Taki21** [comment]
oh wait nvm

**Review by Taki21 — APPROVED** [review]
i liek tutlez and iframez deal with it m9z

**Comment by Ultie0** [comment]
le baguette

**Comment by AvgZing** [comment]
Ultie0 deleted a comment from TheRoyalBlock 14 hours ago?!!!!!!!!!!!!!!! WHYYYY!

**Comment by Vaults1** [comment]
@TheRoyalBlock I deleted one of mine too, they both added nothing to the discussion. 😛

**Comment by AvgZing** [comment]
"le baguette" doesn't either...

**Comment by HimbeersaftLP** [comment]
Discussing about a deleted comment isn't either, and me arguing about this isn't either (you get my point right :D)

**Comment by AvgZing** [comment]
Correcto

**Comment by AvgZing** [comment]
Just testing Fasthub. Thanks @NiekertDev for introducing me to it!

**Comment by Taki21** [comment]
we ever gonna merge it? ;p lol

**Comment by AvgZing** [comment]
Nope. Most complicated pr. Logically it makes less sense to add this. If they wanted a list, visit github. If you really want it more visible, put an iframe of our github page!!!!

**Comment by HimbeersaftLP** [comment]
> Nope. Most complicated pr.

If you call a few lines more code complicated, then I wonder what a simple pr looks like for you...

> Logically it makes less sense to add this.

Where's the logic for that statement?

> If they wanted a list, visit github.

What's the point of your beloved projects page then?

> If you really want it more visible, put an iframe of our github page!!!!

No, just no

**Comment by AvgZing** [comment]
Beloved projects page? While not updated, it was supposed to have an automatic phar builder for each of our plugins, so they can download it from there, not have to compile it on their own...

**Comment by lavender-sys** [comment]
We have poggit.

**Comment by AvgZing** [comment]
poggit loggit. pshhh

**Review by InspectorGadget — COMMENTED** [review]
The code looks good, i'm not able to find any flaws whatsoever. Don't forget to check if this interferes with any other containers or even the page scaling. I'd import ```<hr>``` modules from Bootstrap and then replace it with ```<ul>```.

**Comment by AvgZing** [comment]
remember the lack of necessity

**Review by NiekertDev — APPROVED** [review]
i verie lik te neem himbeercloud

**Comment by AvgZing** [comment]
nice name, bad concept

**Comment by Vaults1** [comment]
image

It looks cool, I'm just not sure about the slider thing, but I don't think you can do anything about it.

**Comment by AvgZing** [comment]
It literally says "check out our projects"... Go to the projects page for that! Unless the "detailed list" I's the project page, in which case it's finr

**Comment by HimbeersaftLP** [comment]
> It literally says "check out our projects"... Go to the projects page for that! Unless the "detailed list" I's the project page, in which case it's finr

The project page is useless, send people to GitHub and you get the same result. My project list however gives an overview of all out projects directly on our webpage (which in itself is a total disaster anyway)

**Comment by AvgZing** [comment]
perhaps... I have an idea

**Comment by HimbeersaftLP** [comment]
Closing because this should be done client side w/o the need of iframes.

**Comment by Vaults1** [comment]
😭

**Comment by InspectorGadget** [comment]
@Ultie0 I think you can hide the slider...

**Comment by HimbeersaftLP** [comment]
Don't worry, I'll make a client sided version shortly :)

**Comment by AvgZing** [comment]
Oo

**Comment by HimbeersaftLP** [comment]
xD

**Comment by ghost** [comment]
I've added back our projects page with no content.

**Comment by ghost** [comment]
https://boxofdevs.com/projects.html

**Comment by ghost** [comment]
I'm using a Cloudflare Worker to fetch repos and modify the webpage.
```js
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

function isEven(n) {
   return n % 2 == 0;
}

/**
 * Respond to the request
 * @param {Request} request
 */
async function handleRequest(request) {
  const response = await fetch('https://api.github.com/orgs/BoxOfDevs/repos', {
  	headers: {
  		'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0'
  	},
  	cf: {
  		cacheTtl: 120
  	}
  })
  const json = await response.json()

  const res = await fetch(request)

const evenHtml = (repo) => `
    <div class="container">
      <div class="row">
        <div class="col-md-12 wwa">
            <h3>${repo.name}</h3>
            ${repo.description ? '<p>' + repo.description + '</p>' : ''}
            <center><a href="${repo.html_url}" class="main">Take a look</a></center>
        </div>
      </div>
    </div>`
const oddHtml = (repo) => `
    <div class="line4">
      <div class="container">
        <div class="row Ama">
          <div class="col-md-12">
            <h3>${repo.name}</h3>
            ${repo.description ? '<p>' + repo.description + '</p>' : ''}
            <center><a href="${repo.html_url}" class="main">Take a look</a></center>
          </div>
        </div>
      </div>
    </div>`

  class ElementHandler {
    element(element) {
      json.forEach((repo, index) => {
        element.append(isEven(index) ? evenHtml(repo) : oddHtml(repo), {
          html: true
        })
      })
    }
  }

  return new HTMLRewriter().on('div#projects', new ElementHandler()).transform(res)
}
```

**Comment by HimbeersaftLP** [comment]
Nathcloud seems better indeed

**Pull request closed without merging**
