### PR TITLE
Remove ad script

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AvgZing** [comment]
We had an adblock blocker on the site??
Or was this the net neutrality 'ad'?

**Comment by SyntaxDragon** [comment]
I removed net neutrality  in the recent PR

**Comment by ghost** [comment]
> We had an adblock blocker on the site??
> Or was this the net neutrality 'ad'?

It's an adblock blocker. I'm kind of amazed it was approved.

**Comment by SyntaxDragon** [comment]
same

**Comment by AvgZing** [comment]
Damn
Keep in mind this was 2017
I think (Can't listen atm but I think) we have "Developers" By steve ballmer linked in audio form at the bottom of the site
We were.... interesting humans

**Comment by ghost** [comment]
> Damn
> Keep in mind this was 2017
> I think (Can't listen atm but I think) we have "Developers" By steve ballmer linked in audio form at the bottom of the site
> We were.... interesting humans

Nobody will ever delete "Developers"
It's staying

**Comment by SyntaxDragon** [comment]
Because it reminds everyone of you and the glory days?

**Comment by ghost** [comment]
> Because it reminds everyone of you and the glory days?

I'd rather not be reminded about myself

**Comment by dragonwocky** [comment]
> Damn
> Keep in mind this was 2017
> I think (Can't listen atm but I think) we have "Developers" By steve ballmer linked in audio form at the bottom of the site
> We were.... interesting humans

Heh... interesting is one way to put it.

**Comment by lavender-sys** [comment]
Oh yeah I remember the A-Ads script. Apparently the ad has a balance of 30 cents in USD at current Bitcoin exchange rates.

**Comment by dragonwocky** [comment]
Yeah we had some crazy idea we could pay for the domain with ad revenue.

**Comment by lavender-sys** [comment]
New idea: We make a little button that allows you to signup for texting alerts for when a new project is released, but instead it acts as one of those texts where it bills you so that you can donate to charity with texting. But instead of the money going to charity it pays for our domain.

**Comment by dragonwocky** [comment]
That sounds like a really bad idea... nobody would sign up lol.

**Comment by lavender-sys** [comment]
Ik. Was mostly a bad idea of how to monetize since the recent trend seems to be making scam ideas to get money. In the discord we came up with Milk a Cow Simulator to scam children.

**Comment by HimbeersaftLP** [comment]
> In the discord we came up with Milk a Cow Simulator to scam children.

Now that's a brand new sentence if I've ever seen one.

**Comment by ghost** [comment]
@HimbeersaftLP 😂😂😂

**Comment by ghost** [comment]
We would be profiting off children already if any of us knew how to make a game

**Pull request merged**
