### PR TITLE
Added "no-download" support for Audio

### PR DESCRIPTION
**Pull request by InspectorGadget**
I've added "no-download" support for the "developers.mp3" file. 

Thanks,
IG

### CODE REVIEW

**Review by AvgZing — APPROVED** [review]
Looks good!

**Review by dragonwocky — APPROVED** [review]
Go ahead :)

**Review by HimbeersaftLP — COMMENTED** [review]
¯\_(ツ)_/¯

**Review by HimbeersaftLP — APPROVED** [review]
¯\\_(ツ)_/¯

**Comment by HimbeersaftLP** [comment]
woops, that was an accident, didn't want to comment above instead of approving...

**Review by Vaults1 — APPROVED** [review]
idk what it does but i approve!

**Comment by AvgZing** [comment]
@Dog2puppy @Taki21 @Ad5001 and @NiekertDev still need to say!

**Comment by InspectorGadget** [comment]
@Ultie0 Why don't you try it from the GitHub branch?

**Comment by InspectorGadget** [comment]
Can i merge? The don't even bother to take a look or approve.

**Comment by AvgZing** [comment]
yeh y not

**Comment by dragonwocky** [comment]
Seriously? Guys for something this basic that only adds to the website we don't need to wait for everyone to approve.... Just like 1 or 2 ppl is enough, the only reason not to merge something is if someone says no...

**Comment by AvgZing** [comment]
ok then

**Pull request merged**
