### PR TITLE
Jekyll Blog

### PR DESCRIPTION
**Pull request by lavender-sys**

### CODE REVIEW

**Comment by AvgZing** [comment]
What does this do?

**Comment by Vaults1** [comment]
I think having it in Jekyll will be better, I'll merge it to test, but if it doesn't work I'll revert it.

**Comment by AvgZing** [comment]
ok but what does it do?

**Comment by Vaults1** [comment]
It means you don't have to update the HTML to add a new post.

**Comment by Vaults1** [comment]
@Dog2puppy it doesn't work

**Comment by AvgZing** [comment]
@Ultie0 Oh nice! Unfortunately, yeah it dnt work

**Comment by lavender-sys** [comment]
@TheDragonRing Gonna restore the branch so I can try to fix it. 
@Ultie0 What doesnt work?

**Comment by AvgZing** [comment]
@Dog2puppy Everything.

**Comment by AvgZing** [comment]
Everything doesnt work

**Comment by dragonwocky** [comment]
If I delete the branch again don't restore it (I'll be doing stuff on my local computer that might hopefully get it working).

**Comment by AvgZing** [comment]
Not worth the effort

**Comment by dragonwocky** [comment]
Yeah ik (changed my mind soon after posting).

**Pull request merged**
