### PR TITLE
The website, but done right

### PR DESCRIPTION
**Pull request by mathhulk**

### CODE REVIEW

**Comment by ghost** [comment]
Why did you change the license?

**Comment by ghost** [comment]
You have some issues with Google PageSpeed. 
img_0098

**Comment by mathhulk** [comment]
Because I did not use the source code from the original website, I was not forced to use your license and thus I changed the license to a more public one. Along with that, the current LICENSE file for the original website is invalid, as the contents does not contain the actual license, but rather a human-readable version that explains what the license is. This human-readable version of the license is not a replacement for the license itself and thus causes that LICENSE file to be invalid.

I will look into the page load issues now.

**Review by dragonwocky — COMMENTED** [review]
This looks great, but we have some other plans. For now, just leave this sitting here. @BoxOfDevs/members see the private chats on Discord for more info.

**Comment by mathhulk** [comment]
Cool, feel free to use this as a template of sorts. Your last website had a lot of issues regarding standards and such, so I would recommend checking back here for that. I tried to make this version as responsive and up to standards as possible.

**Comment by dragonwocky** [comment]
@mathhulk our current site is up to no standards at all, not even our own. It was never meant to be. It's simple a fancy, temporary placeholder. We know how to build responsive/up-to-standards websites (just see our personal sites for examples), this was just a rush job using a template. Appreciate the effort, though.

**Comment by mathhulk** [comment]
I apologize for coming off as rude. I never stated you did not know what you were doing and I know that might seem implied, but I was just saying that this could be used as a reference in the future.

**Comment by dragonwocky** [comment]
You didn't come off as rude. I just just explaining why our site was as it was. Sorry if I implied that I thought you were being rude.

**Comment by ghost** [comment]
Has anybody seen Google Lighthouse?

**Comment by lavender-sys** [comment]
Since when did Google have a lighthouse?

**Comment by ghost** [comment]
It is an application that tests your site to modern web standards, that is my goal with @poggit. You may notice that Poggit loads really slow!

**Comment by lavender-sys** [comment]
Cool. Is it like Google PageSpeed?

**Comment by ghost** [comment]
@Dog2puppy Yes, but PageSpeed it outdated and bad for developers to look at. It has very poor recommendations and is only meant to be used for live sites.

**Pull request closed without merging**
