### PR TITLE
Net Neutrality for July 12

### PR DESCRIPTION
**Pull request by lavender-sys**
On July 12, a popup will be showen to help save net nuetrality. 
fightforthefuture/battleforthenet-widget
battleforthenet.com

### CODE REVIEW

**Comment by Taki21** [comment]
but today is july 13th?

**Comment by lavender-sys** [comment]
@Taki21 Its for 2018. So in the 12th of July in 2018, it will show a message.

**Comment by Taki21** [comment]
oohhhh

**Comment by Taki21** [comment]
i am looking at it

**Comment by Taki21** [comment]
ye i say we merge this.

**Comment by Taki21** [comment]
@Dog2puppy y dont u display it eveyrime someone goes on the website? since net netruality is a big thing?

**Comment by lavender-sys** [comment]
@Taki21 Because that's how their script works.

**Comment by Taki21** [comment]
Wow xD

**Review by Vaults1 — APPROVED** [review]

**Review by HimbeersaftLP — APPROVED** [review]
I'm not from the US and net neutrality isn't a big thing here in Austria AFAIK but I'll approve anyways

**Review by Ad5001 — APPROVED** [review]
Net neutrality is something everyone need and everyone should worry about no matter where they live.

**Comment by Taki21** [comment]
@Ad5001  yath agred

**Comment by AvgZing** [comment]
Agreed with ad5001. Approved, but approving didn't work well on mobile.

**Comment by Vaults1** [comment]
@HimbeersaftLP exactly the same for me, I don't know how American ISP's will affect me but, approving anyway.

**Comment by AvgZing** [comment]
that's more than half the team, merging!

**Pull request merged**
